name: test
on:
- pull_request
jobs:
  vapor_xenial:
    container: 
      image: swift:5.2.3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./install-linux-dependencies.sh
    - run: make test

  vapor_bionic:
    container: 
      image: swift:5.2.3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./install-linux-dependencies.sh
    - run: make test
