name: test
on:
- pull_request
jobs:
  vapor_xenial:
    container:
      image: swift:5.5.0-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./install-linux-dependencies.sh
    - run: make test

  vapor_bionic:
    container:
      image: swift:5.5.0-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./install-linux-dependencies.sh
    - run: make test
